/*
 * File Name  : throughput_top_wrapper_snic_cdc.v
 * Module Name: smartnic_throughput_pl_top
 * Author     : Uchenna Obikwelu
 * Course     : SYSC 4320 – Case Studies in Computer Systems
 * Project    : SmartNIC Packet Classification Accelerator
 * Created    : April 2026
 *
 * Description:
 * Processing Logic (PL) top-level module for the high-throughput SmartNIC
 * FPGA implementation. This module generates packet traffic from a ROM,
 * transfers data across clock domains using an asynchronous FIFO, and
 * performs packet classification using the high-throughput SmartNIC core.
 *
 * Architecture:
 *   - Stage 1: Packet generation from ROM
 *   - Stage 2: Asynchronous FIFO for clock domain crossing (CDC)
 *   - Stage 3: High-throughput packet parsing and classification
 *
 * Notes:
 *   - The write clock is derived from the system clock.
 *   - The read clock is generated by dividing the system clock.
 *   - Used in the FPGA implementation of the high-throughput SmartNIC design.
 *   - Instantiated by the FPGA top-level wrapper.
 */


module smartnic_throughput_pl_top (
    input  wire sysclk,
    input  wire rst,
    output wire valid,
    output wire [3:0] matched_rule_id
);

    wire clk_write;
    wire clk_read;
    reg  clk_read_div;

    assign clk_write = sysclk;
    assign clk_read  = clk_read_div;

    always @(posedge sysclk or posedge rst) begin
        if (rst)
            clk_read_div <= 1'b0;
        else
            clk_read_div <= ~clk_read_div;
    end

    reg  [6:0] rom_addr;
    wire [75:0] rom_packet;

    packet_rom rom_inst (
        .addr(rom_addr),
        .packet(rom_packet)
    );

    reg         wr_en;
    reg  [75:0] ip_packet_in;

    wire [75:0] fifo_dout;
    wire fifo_full;
    wire fifo_empty;
    wire [5:0] ov_wr_pointer;
    wire [5:0] ov_rd_pointer;
    wire [5:0] ov_wr_pointer_gry;
    wire [5:0] ov_rd_pointer_gry;

    async_fifo_top #(
        .PTR_SIZE(5),
        .WIDTH(76),
        .DEPTH(32)
    ) fifo_inst (
        .clk_write(clk_write),
        .clk_read(clk_read),
        .rstn(~rst),

        .wr_en(wr_en),
        .ip_packet_in(ip_packet_in),

        .ov_dout(fifo_dout),
        .os_fifo_full(fifo_full),
        .os_fifo_empty(fifo_empty),

        .ov_wr_pointer(ov_wr_pointer),
        .ov_rd_pointer(ov_rd_pointer),
        .ov_wr_pointer_gry(ov_wr_pointer_gry),
        .ov_rd_pointer_gry(ov_rd_pointer_gry)
    );

    smart_nic_high_throughput_top nic_inst (
        .clk(clk_read),
        .rst(rst),
        .ip_packet(fifo_dout),
        .valid(valid),
        .matched_rule_id(matched_rule_id)
    );

    always @(posedge clk_write or posedge rst) begin
        if (rst) begin
            wr_en        <= 1'b0;
            ip_packet_in <= 76'd0;
            rom_addr     <= 7'd0;
        end else begin
            if (!fifo_full) begin
                wr_en        <= 1'b1;
                ip_packet_in <= rom_packet;
                rom_addr     <= (rom_addr == 7'd74) ? 7'd0 : rom_addr + 1'b1;
            end else begin
                wr_en        <= 1'b0;
            end
        end
    end

endmodule